### ISSUE TITLE
Three derivations might not respect existing instances in scope

### ISSUE THREAD

**Issue by kailuowang** [typelevel/kittens#129] opened 2019-04-17 15:23 UTC
Namely 
```
object pure extends MkPureDerivation
object foldable extends MkFoldableDerivation
object monoid extends MkMonoidDerivation
```
These three are implemented differently from the other derivations. They probably don't respect existing instances.

**Comment by joroKr21** [comment] 2019-04-21 17:59
The problem is that there are other inconsistencies as well. I will write up an issue / proposal what to do.

**Comment by joroKr21** [comment] 2019-05-29 04:36
Fixed by #151, #139 and #132

**Closed by joroKr21** 2019-05-29 04:36 UTC
Labels: Design/refactoring
